### ISSUE TITLE
use version 1.1 or above

### ISSUE THREAD

**Issue by championswimmer** [OpenUserCSS/openusercss.org#1]
https://github.com/OpenUserCSS/openusercss.org/blob/3062dddecb0d46a31501c43a790911ebaaeb0ca0/package.json#L224

**Comment by DecentM** [comment]
Thanks for the notification, I'll be sure to update soon!

**Comment by DecentM** [comment]
Closed with c241a1bf517215585a18591002f2484caabe7c34. Thanks again!
