### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#10]
A simple donation button would go a long way to reward theme authors.
Instead of just a PayPal link, I think  it would be best to just leave the link up to the author to set.

Should the link be set per profile or per theme?

**Comment by Mottie** [comment]
What about a donation button for openusercss.org? 😸

**Comment by DecentM** [comment]
I've not expected to think about getting donations this soon, but I'll set up a Patreon page shortly.

I thought about the button, and I think it's best if authors could set a link in the account details page, and that link will show up on all themes.

**Comment by DecentM** [comment]
Partially done, it's now possible to set a donation link on the account page. I started setting up a Patreon page, it'll probably go live tomorrow.

**Comment by RaitaroH** [comment]
@DecentM What about Makersupport?
I may not look like it but I follow guys like BlackPidgeonSpeaks and Computing Forever and from what I hear Patreon has some vague guidelines and biases.

**Comment by DecentM** [comment]
> What about Makersupport?

This is the first time I've heard about them, but I feel comfortable with Patreon, because I already know their philosophy. If it turns out that there is a huge flaw that I'm not aware of yet, I'm always going to be looking out for alternatives.

**Comment by DecentM** [comment]
I've set up a Patreon page and added a bar about it in the footer. Thanks again!

**Comment by RaitaroH** [comment]
I themed it too.

**Comment by DecentM** [comment]
Awesome! You should probably wait with it until #31 is resolved.

**Comment by RaitaroH** [comment]
I did already pushed the fix tho :P

**Comment by DecentM** [comment]
That's fine, the bar just isn't there in the previous version

**Comment by RaitaroH** [comment]
Good that I themed it fast, because it doesn't show up anymore.

**Comment by DecentM** [comment]
It should show up again now, I fixed the issue that was blocking the update :tada:
