### ISSUE TITLE
Website changelog date and other fields are TOO LARGE.

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#105]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
|  all regular like changelog.md | massive font size  on various fields |
## Steps to Reproduce the Problem

  1. open the changelog on website
  1. marvel at the HUGE text on some fields 
  1. continue looking at it, its B.E.A.U-tiful.

![screenshot-2018-6-14 openusercss](https://user-images.githubusercontent.com/31389848/41439075-4c4a43fa-7021-11e8-9e0d-bb5ec499cb84.png)

## Environment details

  - Site version: 0.9.7 to 1.2.0
  - Browser and version: all
  - Installed extensions: all + 1
  - Operating system: none intra-webs on my brain

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
Thanks, this is already tracked in https://github.com/OpenUserCSS/openusercss.org/issues/49
