### ISSUE TITLE
Promise.prototype.timeout is broken

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#106]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| Not blur out | blur and more blur |

### Before login
![screenshot-2018-6-14 openusercss 3](https://user-images.githubusercontent.com/31389848/41437062-81655c24-701b-11e8-8f0f-de4ef8bbe1aa.png)

### After login
![screenshot-2018-6-14 openusercss 1](https://user-images.githubusercontent.com/31389848/41439356-59759650-7022-11e8-8cb1-0f6f9e3db6f3.png)

Refreshing matters not except for going into user account, first time it wont go into account, requires a refresh at least.

## Environment details

  - Site version: 1.2.0
  - Browser and version: any
  - Installed extensions: NA
  - Operating system: NA

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
Apparently, this is a state related issue. Do you get an error in the console?

**Comment by the-j0k3r** [comment]
when I first login, yes and shows ok, refresh after and bang

![screenshot-2018-6-14 openusercss 4](https://user-images.githubusercontent.com/31389848/41439905-75105768-7024-11e8-90cf-cf06202bbd5a.png)

**Comment by DecentM** [comment]
Ah, this is the issue with the Promise timeout patch @narcolepticinsomniac was getting. Thanks for reporting!
