### ISSUE TITLE
Install link goes to localhost on production

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#107]
Try to install a theme and observe the URL. Unfortunately I don't have a version of OpenUserCSS with a clone of the production database running on my localhost ;)

Client version: 1.3.1

**Comment by hyperfekt** [comment]
Oh weird, I thought the URL was generated the same way for every theme?
Try this theme: https://openusercss.org/theme/5abd48b070bc4a0b00903b9c

**Comment by DecentM** [comment]
It is, apparently when the server renders the page, it inserts localhost for some reason. If you arrive from another page after the clientside javascript takes over, it's fine.

**Comment by Martii** [comment]
@DecentM 
How often do you deploy?

**Comment by DecentM** [comment]
@Martii I deploy whenever I feel like the new version is at least as stable as the currently live one.  
It takes from 2 to 14 minutes, depending on what type of changes I made.  

The commit for this issue, `f16d5a9` will only be in tomorrow's push, since I'm about to end the day :sparkles:

**Comment by DecentM** [comment]
In the meantime you can work around this bug when it happens by navigating to a page (help, for example), then pressing your browser's back button. After that, the installation link will have the correct URL.  
Or, if you use Stylus, the `Install with Stylus` button should work regardless :+1:

**Comment by hyperfekt** [comment]
This still occurs with https://openusercss.org/theme/5b1e761efb52800b0029d522.
Maybe a cache needs to be cleared?

**Comment by DecentM** [comment]
Thanks for letting me know! It seems like there was another part in the source code that has the possibility of generating localhost for the install URL, I've removed that now, will be doing a new release in a few.
