### ISSUE TITLE
HUge, longer than full width notification boxes

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#112]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| decent size notification boxes like before. |HUGE long ones instead|

## Steps to Reproduce the Problem

  1.goto forums user account settings
  1. upload a background header
  1. adjust header
  1. see extra long notification boxes (bottom) that run off screen (longer than 2560x 1440p hahaha. NICE!

![untitled-1](https://user-images.githubusercontent.com/31389848/41501995-33e8f086-71a7-11e8-82c5-6db0801d0cc1.png)

## Environment details

  - Site version: 1.4.1 - 1.4.4 (forums update?) idk I can copy this to forum bugs
  - Browser and version: FF 66.0.2
  - Installed extensions: Stylus
  - Operating system: Win 10 pro

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#20
