### ISSUE TITLE
Show (some indication of more screenhots) by Flickity sliders

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#116]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| On theme page the screenshot should be a visual < > to indicate more screenshots exist| the only visual queue is a mouse cursor change |

## Steps to Reproduce the Problem

  1. gotoo a theme with more than one screeenshot .i.e https://openusercss.org/theme/5b2b99e26dee290b00cd4ae6
  1. see screenshot at top, is there any more? IDK I added more. But I cant see theres any more.
  1. Im a user IDK if that has more screenshots just by looking
  1. Hover over screenshot the cursor changes, Im still not sure I cant see any indication thers more screenshots.
  1. Click and drag... really? Great design,, Dont make me think!

#Possible solutions: (either/or) That doesnt require thinking or hovering.

* Add some left/right overlay tabs in screenshot area.
* Add some pagination type under screenshots (numbers/bullets) 
* Some other visual queue that indicates at a glance theme has more screenshots.

## Environment details

  - Site version: 1.4.6
  - Browser and version: doesnt matter but FF 66.0.2
  - Installed extensions: Stylus
  - Operating system: Windows 10 Pro (you know @DecentM not Linux because Linux you cant see half the bugs though this one also exists there)

----

![screenshots](https://user-images.githubusercontent.com/31389848/41724024-85135c56-7564-11e8-9471-ffcdcb464327.gif)

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by the-j0k3r** [comment]
I changed title, because arrows OVER the slider are not necessarily the best solution due to the fact they are displayed ontop of screenshot area.

The better option is to add an unobtrusive indicator outside of the screenshot bounds or bellow the screenshot area.

**Comment by DecentM** [comment]
Merged into https://github.com/OpenUserCSS/openusercss.org/issues/124
