### ISSUE TITLE
Corrupted content error

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#118]
From https://github.com/OpenUserCSS/openusercss.org/issues/117, by @the-j0k3r 

```
The site at https://openusercss.org/theme/5a2f03e7ba666f0b00b9c829 has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the web site owners to inform them of this problem.
```

**Comment by the-j0k3r** [comment]
:+1:

**Comment by DecentM** [comment]
I've never seen this message before, can you elaborate on where this showed up?

**Comment by the-j0k3r** [comment]
Not complicated clicked the link you posted and bang...

**Comment by DecentM** [comment]
@the-j0k3r I've done some research on this and it seems to be limited to Firefox. All the threads I found also seem to die down after some posts without much of a resolution.  
I think this might be some sort of intermittent network error, in which case I can't do a whole lot about it.  

Does this happen constantly, or has it not happened since?

**Comment by the-j0k3r** [comment]
Alwys.

**Comment by DecentM** [comment]
Please open the developer tools and copy the request response here, so I can start looking at why this happens! It should look like this, just without all the requests but one:  

![screenshot_20180621_235531](https://user-images.githubusercontent.com/4973610/41747532-9845d336-75ae-11e8-9bfa-04ce2c83c792.png)

**Comment by the-j0k3r** [comment]
There is only this

![capture](https://user-images.githubusercontent.com/31389848/41747744-022b5daa-75a7-11e8-85e6-8c15e249386c.PNG)

**Comment by DecentM** [comment]
This is just the DOM of the error page, I can't spot anything related to the cause of the error there.  
You're almost there though. At the top, there should be a network tab that shows the requests that may contain something I can use to figure out a fix for this.  

![firefox-headers](https://user-images.githubusercontent.com/4973610/41748382-ef870676-75b1-11e8-8c58-e19bfb89b920.gif)

**Comment by the-j0k3r** [comment]
There is nothing error wise.

![bug](https://user-images.githubusercontent.com/31389848/41748766-221f8024-75ab-11e8-865a-eda915446fc6.gif)

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
23:27:29.230 Navigated to https://openusercss.org/theme/5a2f03e7ba666f0b00b9c829
23:27:30.933 Error in parsing value for 'transform'.  Declaration dropped.
neterror:3:25

  ```
</details>

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
23:27:29.230 Navigated to https://openusercss.org/theme/5a2f03e7ba666f0b00b9c829
23:27:30.933 Error in parsing value for 'transform'.  Declaration dropped.
neterror:3:25

  ```
</details>

**Comment by DecentM** [comment]
I've looked into this and I don't think I can do much about this. Somehow packet payloads get mutated by the network or a proxy that causes this.
