### ISSUE TITLE
Please add support URL and Project URL for styles in Description + Custom License.

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#119]
There is no way to add this information except manually and then its lost on script update. part of issue #87 

This is definitely not the same as #87, its related but not the same.

Userstyles.org styles are mostly broken or incomplete or only half styles, I have to PM each owner to ask where can I submit fixes...

Also its NOT practical to use forums for discussions/support because you cant track it, and creating tickets for users issues, then I cant ask to update info on GH or they wont look at status.

See this https://github.com/OpenUserCSS/openusercss.org/issues/115#issuecomment-399167767

That information is basic for the description.

**Comment by DecentM** [comment]
Tracked in https://github.com/OpenUserCSS/openusercss.org/issues/87
