### ISSUE TITLE
Adding links to the description of a theme returns error

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#13]
```Syntax Error GraphQL request (5:118) Unterminated string. 4: title: "OpenUserCSS DeepDark", 5: description: "Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme) ^ 6: ```

And the link was just:
```
Homepage here:
https://github.com/RaitaroH/OpenUserCSS-DeepDark```

**Comment by DecentM** [comment]
I can confirm this error, but rather than the link causing the error, it's the newline.
Can you check to see if this is correct?

**Comment by DecentM** [comment]
I want to tackle two issues at the saame time with this, I'm adding markdown support for the theme description and profile bio page.

**Comment by DecentM** [comment]
Fixed with https://github.com/OpenUserCSS/openusercss.org/commit/77cdc07c42af1272125af2b2ab7dd27e95ea1fb4 and https://github.com/OpenUserCSS/openusercss.org/commit/e53195def0a2fcb2b21c2589b605a804648d99a6.

I'll close the issue, but feel free to reopen if it's still giving an error.

**Comment by RaitaroH** [comment]
```
Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme) 

This is a dark theme for OpenUserCSS inspired by [FT DeepDark](https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search). 
This is a dark theme for OpenUserCSS inspired by <a href="https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search">FT DeepDark.</a>
</p>

Github page, with screenshots, available here:
https://github.com/RaitaroH/OpenUserCSS-DeepDark
```

Returns:
```Value assigned to themes.description failed custom validator. Value was Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme) This is a dark theme for OpenUserCSS inspired by [FT DeepDark](https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search). This is a dark theme for OpenUserCSS inspired by <a href="https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search">FT DeepDark.</a> </p> Github page, with screenshots, available here: https://github.com/RaitaroH/OpenUserCSS-DeepDark```

**Comment by RaitaroH** [comment]
```
Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme) 

This is a dark theme for OpenUserCSS inspired by FT DeepDark:
https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search

Github page, with screenshots, available here:
https://github.com/RaitaroH/OpenUserCSS-DeepDark
```

Returns:
```Value assigned to themes.description failed custom validator. Value was Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme) This is a dark theme for OpenUserCSS inspired by FT DeepDark: https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search Github page, with screenshots, available here: https://github.com/RaitaroH/OpenUserCSS-DeepDark```

**Comment by RaitaroH** [comment]
Even with everything inline:
```Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). This is a dark theme for OpenUserCSS inspired by FT DeepDark: https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search Github page, with screenshots, available here: https://github.com/RaitaroH/OpenUserCSS-DeepDark```

```Value assigned to themes.description failed custom validator. Value was Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). This is a dark theme for OpenUserCSS inspired by FT DeepDark: https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/?src=search Github page, with screenshots, available here: https://github.com/RaitaroH/OpenUserCSS-DeepDark```

**Comment by DecentM** [comment]
Hm, for some reason there is a limit of 64 characters on the description.
Let's change that now.

**Comment by RaitaroH** [comment]
But really, tell me if I can put links in words either with the github format or html format <a></a> ok?

**Comment by DecentM** [comment]
You can just put links as is, or you can use markdown
```
[So like this](https://google.com)
```
Or this:
```
Click here: https://google.com
```

**Comment by RaitaroH** [comment]
Ok, thanks. So is like on github, perfect.

**Comment by RaitaroH** [comment]
`Too low length limit #17` XD Maybe if you added a: `Description should only be x char long`

**Comment by DecentM** [comment]
You can also see a preview on the left of the editor, so you can check how it will look.

**Comment by RaitaroH** [comment]
Yeah I noticed. I have to fix that in my theme now.
I also need to check for anything account related on the forum too. I haven't themed anything there.
