### ISSUE TITLE
Help page does not identify installed Stylus

### ISSUE THREAD

**Issue by Kissaki** [OpenUserCSS/openusercss.org#130]
When accessing the [`/help`](https://openusercss.org/help) page it shows a warning that no compatible installed addon was found, and suggests installing Stylus. I have Stylus installed and active and working.

![image](https://user-images.githubusercontent.com/93181/42408705-76a71b94-81d0-11e8-8954-d5e31a1e05a9.png)

  - Site version: 1.5.0
  - Browser and version: Firefox 61.0.1
  - Installed extensions: Stylus (beta)
  - Operating system: Windows 10

**Comment by DecentM** [comment]
Thanks for the report!  
This issue is already being tracked in https://github.com/OpenUserCSS/openusercss.org/issues/91, please follow that for updates!
