### ISSUE TITLE
Wrong placement of 'CATEGORIES' heading on forums page.

### ISSUE THREAD

**Issue by sak6e** [OpenUserCSS/openusercss.org#138]
| Expected behaviour                                           |   Actual behaviour                                      |
| -------------------------------------------------------------  | ------------------------------------------------------- |
| Proper gap between navbar & 'CATEGORIES' | No gap between navbar & 'CATEGORIES'|

## Steps to Reproduce the Problem
  1. Go to https://forums.openusercss.org/

## Solution
  The margin value for the h1 tag is set to 0. The issue can be fixed by increasing it.
![screenshot from 2018-07-28 22-21-04](https://user-images.githubusercontent.com/22349909/43358979-19dcf5fc-92b8-11e8-9cb2-b39242fc708c.png)
I'd like to fix the issue myself, but I'd need help.

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#21
