### ISSUE TITLE
GraphQL error when posting style

### ISSUE THREAD

**Issue by stonecrusher** [OpenUserCSS/openusercss.org#143]
Hi,
I wanted to post [this style](https://github.com/stonecrusher/stylus-UserCSS/blob/master/amazon/amazon.user.css) with two screenshots and custom description to openuserCSS but always receive an error:
![2018-08-14](https://user-images.githubusercontent.com/1388389/44104533-640c1bdc-9fef-11e8-83bc-75c241813de6.png)
No idea what's happening.

**Comment by DecentM** [comment]
Thanks for reporting!  
This is closely related to #92, so I'll close this as this will get fixed with it.
