### ISSUE TITLE
Command "test:unit" not found error

### ISSUE THREAD

**Issue by eight04** [OpenUserCSS/openusercss.org#146]
I followed [CONTRIBUTING.md](https://github.com/OpenUserCSS/openusercss.org/blob/master/CONTRIBUTING.md#running-tests) to clone the repo and run the test, but got a command not found error:

```
D:\Dev\openusercss.org>yarn test:unit
error Command "test:unit" not found.
```

There is no `test:unit` entry in `package.json`. Is this command removed?

## Environment details

  - Site version: master branch 1b1a9fa31b7a33d0008
  - Browser and version:
  - Installed extensions:
  - Operating system: Windows 7 x64

**Comment by eight04** [comment]
The result of `yarn watch`:
```
D:\Dev\openusercss.org>yarn watch
[18:24:43] Using gulpfile D:\Dev\openusercss.org\gulpfile.js
[18:24:44] Starting 'api:fast'...
[18:24:44] Starting 'licenses'...
[18:24:44] Starting 'static:email'...
[18:24:44] Starting 'static:email-templates'...
[18:25:07] Finished 'static:email' after 23 s
[18:25:39] Finished 'licenses' after 56 s
[18:25:39] Finished 'static:email-templates' after 56 s
[18:25:39] Finished 'api:fast' after 56 s
error Command "dev" not found.
error Command failed with exit code 1.
```

**Comment by DecentM** [comment]
Thanks for reporting!  
Regrettably, I haven't updated the documentation or any of the workflows that aren't the Docker one. I'll fix this as soon as I can.

**Comment by DecentM** [comment]
Should be fixed now. I'll close the issue but feel free to continue the conversation if you feel like there's room here to improve.
