### ISSUE TITLE
Unable to use multiple css properties in select variable

### ISSUE THREAD

**Issue by jackbuehner** [OpenUserCSS/openusercss.org#147]
When trying to use multiple css properties per variable, the following errors are recieved:
For existing themes: `GraphQL error: Non-classified error (with no error code): Cannot convert object to primitive value`
For new themes: `GraphQL error: Non-classified error (with no error code): Value assigned to variableoptions.value failed custom validator. Value was --background-color-1: #c72a2a;--background-color-2: #e4e4e4;--background-color-3: #fff;--background-color-4: #e5e5e5;--background-color-tabbar: #f3f2f1;--background-color-5: #484644;--text-color-1: #000000;--text-color-2: #1f1f1f;--text-color-2-title: #fff;--text-color-3: #232323;--text-color-4: #424242;--text-color-5: #616161;--text-color-blue: #78b4f8;--text-color-red: #f00;--button-background: #e1e1e1;--button-background-hover: #E5F1FB;--button-background-active: #CCE4F7;--button-border-color: #adadad;--button-border-color-hover: #0078D7;--button-border-color-active: #005499;--button-border-color-focus: #0078D7;--button-border-width-focus: 2px;--button-padding-focus: 3px 19px;--font: #dd0000;--ribbon-shadow: 0px 6px 10px -3px rgba(0,0,0,0.2);`

| Expected behaviour | Actual behaviour |
| ----- | ----- |
| Allow multiple properties per variable | Receive an error |

## Steps to Reproduce the Problem

  1. Create new theme/edit old theme
  2. Add a variable of type `select`
  3. For value, use `--background-color-1: #c72a2a;--background-color-2: #e4e4e4;--background-color-3: #fff;--background-color-4: #e5e5e5;--background-color-tabbar: #f3f2f1;--background-color-5: #484644;--text-color-1: #000000;--text-color-2: #1f1f1f;--text-color-2-title: #fff;--text-color-3: #232323;--text-color-4: #424242;--text-color-5: #616161;--text-color-blue: #78b4f8;--text-color-red: #f00;--button-background: #e1e1e1;--button-background-hover: #E5F1FB;--button-background-active: #CCE4F7;--button-border-color: #adadad;--button-border-color-hover: #0078D7;--button-border-color-active: #005499;--button-border-color-focus: #0078D7;--button-border-width-focus: 2px;--button-padding-focus: 3px 19px;--font: #dd0000;--ribbon-shadow: 0px 6px 10px -3px rgba(0,0,0,0.2);`

## Environment details

  - Site version: v1.9.1
  - Browser and version: Firefox Developer Edition 63.0b2 (64-bit)
  - Installed extensions: Stylus
  - Operating system: Windows 10 Pro Version 1809 (Build 17751.1)

**Comment by DecentM** [comment]
Thanks for reporting and for fully filling the template out!  
This is closely related to #92, so I'll close this as this will get fixed with it.
