### ISSUE TITLE
If you want you can add my dark theme to the project

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#15]
https://github.com/RaitaroH/OpenUserCSS-DeepDark
That would be pretty f*cking awesome.

**Comment by DecentM** [comment]
WOW! I love the variations! I don't think the editor is capable of complex configuration yet, but I can definitely see the need for it. Thanks!

I don't want to add a theme chooser to the site, because that would duplicate the functionality that already exists on the site and in Stylus.

**Comment by DecentM** [comment]
What we can do I think, is to have a feature where anyone can create collections of themes. How's it sound?

**Comment by RaitaroH** [comment]
No I don't think that having the theme chooser in the website itself. Just have the theme on the front page. That is enough. Also the color palettes are the same across all of my themes. I think that I covered any possible color palette desire blue, green, yellow, red, purple, you name it. (just so you know I don't really care about those for the most part, they are there for other people, especially for Linux users)

I was suggesting to just move the repo from me to the organization. It doesn't really affect me but would be better than me sending invitations to you or Mottie or somebody else to contribute to the theme. You know, keeping things cleaner this way.  (also is not like I want to be a part of an organization or anything...  *INSERT TSUNDERE NOISE HERE* :P )

You could have tags for themes for instance to make searches easier. So you can make a special tag OpenUserCSS_THEME for example. And all OSCss themes will be found there. The author can simply add tags like that. Kinda like on github I guess. So for me: openusercss, dark theme, deepdark, breeze dark, arc dark, vertex dark, mint-y-dark etc (you get the point). Also, remember the tags across other thmes please.... I always use the same stuff as you can guess so would be really cool to have a default tags stuff. 
I really want the search feature to top notch, I mean heck, on USO I can't find almost anything, is that terrible.

**Comment by DecentM** [comment]
Ah, yes, that makes more sense.
Theme labels are alreay on the roadmap, it will be implemented when I'm done with more critical functionality, or if someone picks it up. Then there can be featured tags. This way would be more fit for general use, because anyone would be able to create tags, not just me.

I invited you, so you can migrate your repo into the organization :tada:

**Comment by RaitaroH** [comment]
![image](https://user-images.githubusercontent.com/19552720/34452077-165f10e0-ed40-11e7-85a2-e6924e73e47a.png)
🥇
