### ISSUE TITLE
Parse pasted usercss metadata

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#16]
From #12
The API adds the usercss metadata to the theme code on request.
What I think should happen is that when the source is pasted into the editor, the UI should parse the metadata (if any), and set the variables, title, version and description accordingly.

**Comment by RaitaroH** [comment]
I added `PLEASE INSTALL FROM GITHUB FOR NOW.` to the description of the dark theme just so people know.
Now, I could try and remove the header but then I will have to default on one color palette (see #18)

**Comment by RaitaroH** [comment]
If we are at this.
```
/* ==userstyle==
@name OpenUserCSS DeepDark
@description Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). 
## ![#DA4453](https://placehold.it/15/#DA4453/000000?text=+) `PLEASE INSTALL FROM GITHUB FOR NOW`
@version 1.2.0
@namespace https://openusercss.org/theme/5a4605de961b8c0b001f2476
@homepageURL https://openusercss.org/theme/5a4605de961b8c0b001f2476
@author RaitaroH (https://openusercss.org/profile/5a433adb2ef4870b000695a5)


==/userstyle== */

/* ==UserStyle==
@name OpenUserCSS DeepDark
@namespace github.com/OpenUserCSS/OpenUserCSS-DeepDark
@homepageURL https://github.com/OpenUserCSS/OpenUserCSS-DeepDark
@version 1.2.0
@updateURL https://raw.githubusercontent.com/OpenUserCSS/OpenUserCSS-DeepDark/master/OpenUserCSSDeepDark.user.css
@description OpenUserCSS dark theme
@author RaitaroH
@license GNU-V3.0
```
The header added by the site doesn't provide `@updateURL`. Might be a problem, I don't know. Also as you can see my description there ends up on another line, it MIGHT also cause problems, not sure.

**Comment by RaitaroH** [comment]
@DecentM 
Also as a suggestion, can't you add say, a check button `CHECK THIS IF THIS THEME IS USER.CSS FORMAT!` or something like that? If checked the header won't be added. Also would be nice to have that control in the settings for the account, in order to apply this across all themes you have, and not set this EVERY TIME.

**Comment by DecentM** [comment]
According to the wiki on Stylus's repository (https://github.com/openstyles/stylus/wiki/Usercss#usercss-metadata), there is no such thing as @updateURL, but I suppose I could add the property without really harming anything.

The way I'm doing it is much simpler than that, from the perspective of new theme authors. If a pasted style has valid usercss headers, the editor will grab the properties and change the edited theme accordingly. Depending on your timezone, you may be able to test this out later today.

**Comment by RaitaroH** [comment]
```
The way I'm doing it is much simpler than that, from the perspective of new theme authors. If a pasted style has valid usercss headers, the editor will grab the properties and change the edited theme accordingly. Depending on your timezone, you may be able to test this out later today.
```
My suggestion was something like: `Well, I can't fix this so might as well make a workaround`.

**Comment by DecentM** [comment]
A new build is up that parses the usercss definition, except variables. Can you test that what is in so far works?

**Comment by RaitaroH** [comment]
Maybe it didn't kick in yet.

**Comment by DecentM** [comment]
Check the footer for the version string. This is in 09eb1c0 and onwards.
It can take a short time for the update to be rolled into the serviceworker cache.
Once it's downloaded, the new version will load the next time you open the website.

**Comment by RaitaroH** [comment]
4.0 Client version: 09eb1c0
Still doesn't work for me.

**Comment by DecentM** [comment]
So just to be clear, if you go to edit or create a new theme, is there not a "Parse source code on input event" switch?

**Comment by RaitaroH** [comment]
Wait? You added a switch? XD Let me check.

**Comment by RaitaroH** [comment]
So... if I activate the switch the theme is broken:
```
/* ==userstyle==
@name OpenUserCSS DeepDark
@description Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). 
## ![#DA4453](https://placehold.it/15/#DA4453/000000?text=+) `PLEASE INSTALL FROM GITHUB FOR NOW`
@version 1.2.0
@namespace https://openusercss.org/theme/5a4605de961b8c0b001f2476
@homepageURL https://openusercss.org/theme/5a4605de961b8c0b001f2476
@author RaitaroH (https://openusercss.org/profile/5a433adb2ef4870b000695a5)


==/userstyle== */

@-moz-document domain("openusercss.org")  {
  /*Theme made by RaitaroH @https://github.com/RaitaroH/OpenUserCSS-DeepDark*/

  /*GNU General Public License v3.0*/

  /*1.2.0*/

  /*Main color variables*/

  :root {
    /*User colors*/
    --main-color: ;
    --main-background: ;
    --second-background: ;
    --hover-background: ;
    --main-text: ;
    --dimer-text: ;
    --shadow: 0 1px 0.5px rgba(0,0,0,0.13);
```
All the variables for Stylus get fucked. 
Also Stylus hangs:
![screenshot_20180105_170945](https://user-images.githubusercontent.com/19552720/34614776-442f71e0-f23b-11e7-9b53-59f9fa6b6c3a.png)

**Comment by RaitaroH** [comment]
On another note, I can't disable the damn thing either. It seems that the site notices the Stylus header and then goes ahead and does the above.

**Comment by DecentM** [comment]
Looks like the theme description is just echoed back as markdown instead of a nice render.
Variables aren't parsed yet, because they're more complex than the other properties.

**Comment by RaitaroH** [comment]
Well, good work then. For now my themes still won't work unfortunately.

**Comment by DecentM** [comment]
If you want, you can disable the switch to skip this logic, as it's rather incomplete right now. Thanks for testing it, really useful stuff!

**Comment by RaitaroH** [comment]
```
On another note, I can't disable the damn thing either. It seems that the site notices the Stylus header and then goes ahead and does the above.
```

**Comment by narcolepticinsomniac** [comment]
I'm checking this style as a reference periodically, and it still installs incorrectly. I know you've got a lot on your plate, but this should be a priority.

**Comment by Mottie** [comment]
> there is no such thing as @updateurl

There is, but it's internally set from the page where the style was installed- [ref](https://github.com/openstyles/stylus/pull/134#issuecomment-321575913)

**Comment by Mottie** [comment]
I just encountered an error `Cannot convert object to primitive value`. Since #18 was closed, I'll post it here.

I was trying to add the [GitHub Commit Limits](https://github.com/StylishThemes/GitHub-Commit-Limit/blob/master/github-commit-limit.css) style (not usercss). And set the following values:

* Theme description: "x" (not required to see error)
* Version `1.2.0`
* Screenshot: none (not required to see error)
* Experimental switch: Off
* Code: The unmodified css from the repo, linked above.
* Add color option:
  * Title: `Limit Background Color`
  * Variable name: `overlimit-color`
  * Color: `#FFDDDD`

Clicking "Save theme" shows the following error in the console:

> browser.js:1 Error: Cannot convert object to primitive value
    at AuthenticationError.ExpectedError (https://openusercss.org/browser.js:1:3181608)
    at new AuthenticationError (https://openusercss.org/browser.js:1:3181934)
    at https://openusercss.org/browser.js:1:3125376
    at tryCatch (https://openusercss.org/browser.js:1:2307692)
    at Generator._invoke (https://openusercss.org/browser.js:1:2307297)
    at Generator.prototype.(anonymous function) [as throw] (https://openusercss.org/browser.js:1:2307976)
    at step (https://openusercss.org/browser.js:1:3116736)
    at https://openusercss.org/browser.js:1:3116897
    at <anonymous>

**Comment by DecentM** [comment]
Thank you for the detailed report! I'll fix this along with this issue's feature.

**Comment by DecentM** [comment]
I've gotten the first version of parsing sort of working. Look out for version 0.6.x soon!
For some reason, the abstract syntax tree generated by the parser doesn't include inline comments. This breaks the uso preprocessor format. I'll see what I can do about this.

**Comment by DecentM** [comment]
I pushed an update that includes the above :tada:
When you load the site now, it's going to display an error about API fields. This is normal. Once you refresh, the new version should be running (once again, check the footer!).

**Comment by DecentM** [comment]
I also expect more errors to pop up as usual, I'm not confident that the code is super stable.

**Comment by Mottie** [comment]
I'm working on the parser code I've extracted from Stylus. I'll try to get it done today and post it. We plan to publish it on npm.

**Comment by DecentM** [comment]
Awesome!
Feel free to look here as well if you want to: [c5931c0bd9f6d0c235111bfeaa703006a2e8bbaf/src/shared/usercss-parser.js](https://github.com/OpenUserCSS/openusercss.org/blob/c5931c0bd9f6d0c235111bfeaa703006a2e8bbaf/src/shared/usercss-parser.js)

**Comment by RaitaroH** [comment]
It sure got better than before. Now the only fix needed is the variables. Nice work!
```
/* ==userstyle==
@name OpenUserCSS DeepDark
@description Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). - PLEASE INSTALL FROM GITHUB FOR NOW
@version 1.2.3
@namespace https://openusercss.org/theme/5a4605de961b8c0b001f2476
@homepageURL https://openusercss.org/theme/5a4605de961b8c0b001f2476
@author RaitaroH (https://openusercss.org/profile/5a433adb2ef4870b000695a5)


==/userstyle== */

@-moz-document domain("openusercss.org")  {
  /*Theme made by RaitaroH @https://github.com/RaitaroH/OpenUserCSS-DeepDark*/

  /*GNU General Public License v3.0*/

  /*1.2.3*/

  /*Main color variables*/

  :root {
    /*User colors*/
    --main-color: ;
    --main-background: ;
    --second-background: ;
    --hover-background: ;
    --main-text: ;
    --dimer-text: ;
    --shadow: 0 1px 0.5px rgba(0,0,0,0.13);
```

**Comment by Mottie** [comment]
It's done - https://github.com/StylishThemes/usercss-parser - please review.

**Comment by RaitaroH** [comment]
Very nice @Mottie.

**Comment by DecentM** [comment]
Looks great at first sight, I'll have a go at switching to it

**Comment by DecentM** [comment]
I fixed my regex parsing so that it should be fully complete. Please try and let me know, @RaitaroH 
After I've been able to work on the other issues, I'll revisit this and implement the parse-usercss module, which will have hopefully matured by then.
@Mottie Can you please ping me when you feel like the module is stable?

**Comment by RaitaroH** [comment]
@DecentM The double header was fixed. The variables under `:root`: also stay BUT the variables in the header get removed.   Not that big of a deal for most people, but my themes are very variable heavy and  this makes them unusable (weeeel... if people just cop y paste some stuff then is fine but the theme would seem broken at first)
Regardless, great work guys,

Here is the head of the code right now:
```
/* ==userstyle==
@name OpenUserCSS DeepDark
@description Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). - PLEASE INSTALL FROM GITHUB FOR NOW
@version 1.2.4
@namespace https://openusercss.org/theme/5a4605de961b8c0b001f2476
@homepageURL https://openusercss.org/theme/5a4605de961b8c0b001f2476
@author RaitaroH (https://openusercss.org/profile/5a433adb2ef4870b000695a5)


==/userstyle== */



@-moz-document domain("openusercss.org") {

/*Theme made by RaitaroH @https://github.com/RaitaroH/OpenUserCSS-DeepDark*/

/*GNU General Public License v3.0*/

/*1.2.4*/

	/*Main color variables*/
	:root
	{
		/*User colors*/
		--main-color: /*[[mainColor]]*/;
		--main-background: /*[[mainBackground]]*/;
		--second-background: /*[[secondBackground]]*/;
		--hover-background: /*[[hoverBackground]]*/;
		--main-text: /*[[mainText]]*/;
		--dimer-text: /*[[dimerText]]*/;

		--shadow: 0 1px 0.5px rgba(0,0,0,0.13);
```

**Comment by DecentM** [comment]
> the variables in the header get removed  

I can see that this happens to the theme on the site, but it works when I try locally. Can you try reuploading the theme? (edit the theme, delete the code, paste from GitHub)

**Comment by RaitaroH** [comment]
@DecentM It is finally done. Thank you.
