### ISSUE TITLE
What is the format for adding options?

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#18]
Example theme:
```
/* ==UserStyle==
@name           Test
@namespace      github.com/openstyles/stylus
@version        0.1.0
@description    A new userstyle
@author         Me
==/UserStyle== */
@-moz-document domain("forums.openusercss.org") {

.categories .teaser .user-avatar
	{
    border-radius: /*[[avatar]]*/ !important;
	}
a, a:hover
{
  color: /*[[linkColor]]*/ !important;
}
}
```

![image](https://user-images.githubusercontent.com/19552720/34451900-f8b6e9ee-ed3c-11e7-9c71-9dd955cbf91a.png)

I also tried not to add `%` there  but in the code.

**Comment by RaitaroH** [comment]
I just get:
`Cannot convert object to primitive value`

I tried `/*[[linkColor]]*/`, `[[linkColor]]`, `linkColor`

**Comment by DecentM** [comment]
I haven't been able to confirm this yet, but I feel like more testing is needed on my side on preprocessor format and different options object states.

**Comment by RaitaroH** [comment]
Just have a wiki or something. Some guidelines. You don't have to go with what USO had. Maybe consult with the stylus guys, to have better integration with stylus or something :P

**Comment by RaitaroH** [comment]
But just so you know, I don't personally need the options at all. My user.css is configured with the options that work in Stylus so, it doesn't bother me. I want #16 to be fixed way more :P

**Comment by DecentM** [comment]
These two are related to each other, fixing that would take care of this.
Closes #16

**Comment by DecentM** [comment]
closes #16

**Comment by DecentM** [comment]
Connects to #16

**Comment by DecentM** [comment]
I'll close this in favour of #16 to get the duplicate version off the list, but feel free to continue the conversation here or there.
