### ISSUE TITLE
Scrollbar github embeded links in the forum chat

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#24]
![image](https://user-images.githubusercontent.com/19552720/34459792-e652f2e0-ee02-11e7-9a6f-f862245a610f.png)

```
.github-embed pre
{
display: none;
}
```
Then you get:
![image](https://user-images.githubusercontent.com/19552720/34459799-263f0056-ee03-11e7-9dae-d8cad3d74651.png)

**Comment by DecentM** [comment]
There's actually text there, but the dark theme doesn't change the color of it. Without the theme, it looks like this:
![Screenshot](https://i.imgur.com/DhdqwA9.png)

**Comment by RaitaroH** [comment]
aaa

**Comment by RaitaroH** [comment]
XD
My bad then.
