### ISSUE TITLE
Autosrolling in the forum chat lags one message behind

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#25]
[screencast1.zip](https://github.com/OpenUserCSS/openusercss.org/files/1595018/screencast1.zip)

**Comment by DecentM** [comment]
I can confirm this, not sure how one would go about fixing it, it's probably in NodeBB core, I'll take a look at some point

**Comment by RaitaroH** [comment]
Song:
https://www.youtube.com/watch?v=DrOI1RepFjU

**Comment by DecentM** [comment]
I'll also look into this one on the 2nd

**Comment by DecentM** [comment]
:tada: Should be fixed now, if it's still happening for you, let me know!
