### ISSUE TITLE
Allow anonymous forum posting via captcha

### ISSUE THREAD

**Issue by narcolepticinsomniac** [OpenUserCSS/openusercss.org#26]
For people with commitment issues.

**Comment by DecentM** [comment]
I've scheduled a maintenance window for the forums. I'll look into this and if there's a relatively straightforward way to do this, it'll happen.

**Comment by DecentM** [comment]
I've turned on guest posting in the theme requests section along with spam checking.
If it doesn't create lots of trouble, I'll enable it on all categories :v:
