### ISSUE TITLE
Recent discussions on author themes

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#29]
As userstyles has. It will make it much easier for theme creators to see bug reports. And no, having notifications will not work because you get notifications for other things too.
![image](https://user-images.githubusercontent.com/19552720/34461336-4f8cb38c-ee2f-11e7-998e-9630c628468d.png)

**Comment by DecentM** [comment]
Yep, this is already planned.
Closing this one in favour of #14, but if you think this is different feel free to let me know!
