### ISSUE TITLE
[Vue warn]: Error in created hook: "TypeError: this.editedTheme is null"

### ISSUE THREAD

**Issue by jerone** [OpenUserCSS/openusercss.org#3]
Interesting project. I just created an account, but when trying to create a new theme, I get an empty screen with the following error in the console:
```
[Vue warn]: Error in render: "TypeError: e.editedTheme is null"

found in

---> <Anonymous>
       <Root>
```

**Comment by DecentM** [comment]
Thanks for the report!
It looks like a bug slipped into the live version. I'll look into this and fix it with the next update.

**Comment by DecentM** [comment]
Fixed! It's going to go live in a few minutes. If the error still shows, please press CTRL+F5 to clear the serviceworker cache!

**Comment by jerone** [comment]
Confirmed fixed.
