### ISSUE TITLE
Markdown issues in the description of themes

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#33]
Code:
```
Host your code in the dark. May the dark be kinder on thine eyes. (openusercss.org dark theme). 
![#DA4453](https://placehold.it/15/#DA4453/000000?text=+) `PLEASE INSTALL FROM GITHUB FOR NOW`






Emphasis, aka italics, with *asterisks* or _underscores_.

Strong emphasis, aka bold, with **asterisks** or __underscores__.

Combined emphasis with **asterisks and _underscores_**.

Strikethrough uses two tildes. ~~Scratch this.~~
```

![image](https://user-images.githubusercontent.com/19552720/34466512-e1af6700-eede-11e7-839a-efeba8c2c625.png)
As you can see new lines get removed and bold text disappears.

**Comment by RaitaroH** [comment]
Also is there a better way to add colored text that I don't know about?

**Comment by RaitaroH** [comment]
So yeah just take:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
for a test drive.

Lists are somewhat ok.  Images don't show up. Code is fine. Tables not so much 
:P

**Comment by DecentM** [comment]
It's not possible to add multiple lines in markdown by just pressing enter.
If you want to space content out, you can put a bunch of dashes below an empty line.
Bold text disappearing is courtesy of the dark theme :wink:

Here's an example:
![Screenshot](https://i.imgur.com/G8NeQNp.png)

I'll close this, but feel free to let me know if I missed something!

**Comment by RaitaroH** [comment]
Good to know. I will try to fix the data selectors in the theme.
