### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#34]
Search decentm
![image](https://user-images.githubusercontent.com/19552720/34466706-4a3b49ea-eee6-11e7-9a07-d0b6c88b305d.png)

Search: deepdark
![image](https://user-images.githubusercontent.com/19552720/34466707-6092bebc-eee6-11e7-86e6-3bb38b0eb437.png)

**Comment by DecentM** [comment]
Yep, already know about this, working on a solution ATM

**Comment by DecentM** [comment]
This only seems to happen when the results contain a user object, I think I also know exactly where the issue is.

**Comment by RaitaroH** [comment]
Good then.
