### ISSUE TITLE
Add more theming classes

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#35]
Classes that start with `.ouc-` are meant to help theme authors who want to write themes for the site.
There needs to be way more of those to be helpful.

If anyone wants to pick this up before me, it's pretty easy to add classes to the templates.
Files needed to resolve this are here (any file in these directories that have the `.pug` extension):
- `src/components/bits`
- `src/components/elements`
- `src/components/pages`
- `src/views/layouts`

**Comment by tkosamja** [comment]
Maybe I'm seeing something wrong but aren't the directories these:

- `src/components/bits`
- `src/components/elements`
- `src/components/pages`

instead of the ones you posted?

**Comment by DecentM** [comment]
That's correct, fixed it. Thanks!

**Comment by RaitaroH** [comment]
Closed https://github.com/OpenUserCSS/OpenUserCSS-DeepDark/issues/3  in favor of this.

**Comment by DecentM** [comment]
Please take a look at the new classes and let me know if there's need for more!

**Comment by RaitaroH** [comment]
When I have more time. For now the theme works and is fine.
