### ISSUE TITLE
Embeded github links show open for too long (after closed)

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#38]
https://forums.openusercss.org/topic/7/say-hello-here/10

So yeah, I closed those a while ago (40 minutes).

**Comment by DecentM** [comment]
I'm not sure what you mean by "for too long". Can you post a screenshot or a screencast?

**Comment by RaitaroH** [comment]
Well, 
![image](https://user-images.githubusercontent.com/19552720/34490799-adeec760-efe9-11e7-8802-58d1e47f8ae3.png)

#4  RaitaroH closed this 10 hours ago
#5  RaitaroH closed this 9 hours ago

**Comment by RaitaroH** [comment]
See what I mean? The status of this github embeds can be used by users to check if something was fixed. If it shows "open" for 24 hours after the theme was closed it seems that the problem took a long time to be fixed.

**Comment by DecentM** [comment]
Oh, I get it now. Github embeds are cached by the plugin, but it could also be that they're frozen in time when you post them.
Let's wait a day and see if it still shows "open"

**Comment by RaitaroH** [comment]
@DecentM They closed now.

**Comment by DecentM** [comment]
Ah, so it was the cache. I'll close this, because that caching is needed in order to stay within GitHub's rate limiting.
Thanks for checking!
