### ISSUE TITLE
Add a changelog that takes from github commits

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#39]
So the idea is to have a changelog/history whatever that takes from github commits. I always copypasta the commit names to USO anyway. 

Also I am eagerly waiting to fix the double header for .user.css and add the github integration.

**Comment by RaitaroH** [comment]
I would like it to go all the way back too, showing all the commits. But it would be nice to only show the last 3 commits for people to see.

**Comment by DecentM** [comment]
This would be super cool, thanks!

**Comment by DecentM** [comment]
Part one is complete, the footer now contains the current client version, which is also passed to the error handler.

**Comment by DecentM** [comment]
From https://github.com/OpenUserCSS/openusercss.org/commit/a42049196a15f118a77d2a6f45bfded568ebd792 onward, the client will show a changelog link in the footer.
While I was working on this, I also implemented automatic versioning and uploaded some docs on contributing :tada:

**Comment by RaitaroH** [comment]
Nice.
If you finish the github linking I can port all my themes right away.
