### ISSUE TITLE
Signatures should extend all the way even when the message is too long.

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#40]
Here are the screenshots to show you what I mean:
How it is:
![image](https://user-images.githubusercontent.com/19552720/34491225-537c020a-efeb-11e7-8894-cbc2ef15003d.png)

How it should be:
![image](https://user-images.githubusercontent.com/19552720/34491210-43adb3dc-efeb-11e7-950e-9571ed1ae8b5.png)

Fix:
```
.col-sm-10.col-md-10.col-lg-10:not(.post-content)
{
    width: 100%;
}
```

**Comment by DecentM** [comment]
Thank you!

I modified your fix to
```css
.post-content + div {
    width: 100%;
}
```
