### ISSUE TITLE
What is with this .avatar.avatar-rounded class

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#41]
```
.avatar.avatar-rounded {
 border-radius:50%
}
```
How it is:
![screenshot_20180102_183529](https://user-images.githubusercontent.com/19552720/34491467-33c80282-efec-11e7-9334-5f198ab937b0.png)

How it would be if the rule was applied:
![screenshot_20180102_183602](https://user-images.githubusercontent.com/19552720/34491470-3621d85a-efec-11e7-81ea-01b98361f480.png)

I mean obviously you don't have it rounded, nor does it look good either. Not a big problem, but just pointing out.

**Comment by DecentM** [comment]
This class comes from https://github.com/revir/nodebb-plugin-cards2, but the plugin doesn't use it. Since it doesn't affect the interface at all, I think it's fine.

I'll close this, but feel free to continue the conversation if you want!
