### ISSUE TITLE
"The e-mail field must be a valid email" as soon as I start typing

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#42]
When logging in to https://openusercss.org/login, as soon as I start typing a box shows up saying "The e-mail field must be a valid email."
It's not a big issue, just a visual detail.

**Comment by DecentM** [comment]
I mean it's not wrong :wink:, but yeah, I also think it's unnecessary to validate input before pressing the login button.

**Comment by DecentM** [comment]
Closed with https://github.com/OpenUserCSS/openusercss.org/commit/25b77faaa0a1e2733860c51ad1d4217e277da140 :tada:
