### ISSUE TITLE
Network error when the site loads

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#43]
![image](https://user-images.githubusercontent.com/19552720/34516837-366f3fba-f081-11e7-9fd9-ae40ec01f653.png)

**Comment by DecentM** [comment]
Duplicate of #44, thanks for reporting!

**Comment by DecentM** [comment]
Looks like the API is down, I'm taking a look right now

**Comment by RaitaroH** [comment]
```Duplicate of #44, thanks for reporting!```
@DecentM Now, now. Isn't #44 a duplicate of #43? 😏

**Comment by DecentM** [comment]
You're right, but I was just typing it quickly so I can get to fixing it instead of opening the other issue.
But yeah, that's why I commented here :+1:

**Comment by RaitaroH** [comment]
XD
