### ISSUE TITLE
Error: Network error: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#44]
Captured by Sentry

```
Error: Network error: NetworkError when attempting to fetch resource.
  at ExpectedError (/browser.js:5:3116715)
  at _callee5/< (/browser.js:5:3066226)
  at tryCatch (/browser.js:5:2249141)
  at wrap/generator._invoke</< (/browser.js:5:2248749)
  at defineIteratorMethods/</prototype[method] (/browser.js:5:2249423)
...
(23 additional frame(s) were not displayed)
```

**Comment by DecentM** [comment]
An attempt to fix this is being built

**Comment by DecentM** [comment]
I was able to fix the immediate issue. The API is up, because I removed the routine implemented for #31, as it was causing the API to not start up, as the schema has been changed for ratings.

Because of this, the currently cached client version will display an error saying "Cannot query field 'rating' on type "Theme"...", this is normal

I'm leaving this open for a short time while I'm testing if removing the routine was really the right solution

**Comment by RaitaroH** [comment]
@DecentM Does the screenshot not found issue relate to this one too?
![image](https://user-images.githubusercontent.com/19552720/34531926-c1e104da-f0bc-11e7-91fb-1f31627485b8.png)
I updated the theme twice just to make sure, but every time the image just doesn't display, and the link to it isn't saved.

Also, have an image with the right aspect ratio so it is not cropped like that.

**Comment by DecentM** [comment]
It looks like the original issue was fixed for good.

Thanks for the recrop! I'll see if I can use it in some way.
This error image is very generic, and it appears not only for screenshots, but also in place of any image that fails to load for whatever reason. (The site logo, Patreon, etc). It's impossible to cover every case.
