### ISSUE TITLE
The chat entries in the icon next to notifications is empty

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#45]
So you get a notif if somebody messages you, but if you click the chat button you can't see any of your chats. Is just blank `li`s.

**Comment by DecentM** [comment]
Don't know if this is a bug in the theme or NodeBB.
I'll have to figure out which component causes this fault in the next maintenance window

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#4
