### ISSUE TITLE
Can't access chats

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#46]
When I first click the chat icon, only the following appears, even though I add 1 notification: 
![chat](https://user-images.githubusercontent.com/26143003/34567760-7824bd92-f15b-11e7-8057-33eef6e907d7.png)

I tried clicking "See all chats" and it sent me to https://forums.openusercss.org/user/[myusername]/chats
![chat2](https://user-images.githubusercontent.com/26143003/34567877-deaeae4c-f15b-11e7-9410-89fccb89ef63.png)

After selecting the chat the url changed to https://forums.openusercss.org/user/[myusername]/chats/3 but nothing happened. 
I was able to use the chat by going to the person I was talking and selecting chat though.
PS: Tried in different browsers

**Comment by DecentM** [comment]
We have #45 for the first issue, the second one is new, thanks!

**Comment by DecentM** [comment]
I'll look into this the next time I take the forums down for maintenance. It looks like that will have to come sooner than later.

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#3
