### ISSUE TITLE
Chat should allow posting of images (drag&drop)

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#47]
I mean really. I tend to post pics a lot so this would be really useful for me. Thanks DM.

**Comment by RaitaroH** [comment]
If at it... preview like Discord would be welcomed.

**Comment by DecentM** [comment]
As far as I know, NodeBB doesn't have this feature in it, nor is there a plugin to enable it.
Making this happen would require a lot of time that I could spend fixing issues and adding features to the site.

If you find a plugin that does this, I'd be happy to configure it, but I think developing the feature from scratch if super out of scope for the foreseeable future.

**Comment by RaitaroH** [comment]
Understood.

**Comment by RaitaroH** [comment]
https://github.com/NodeBB/NodeBB/issues/613

**Comment by RaitaroH** [comment]
Further searching reveals:
https://community.nodebb.org/topic/10934/hosts-and-attachments/3

> Q: How does NodeBB handle attachments? My forum will need to have the ability to upload zips, 7zs, and image files. Can NodeBB handle a good amount of attachments?

> A: NodeBB will handle whatever you want to throw at it. You will likely need NGINX setup, and this is where you would set the allowed file types and upload sizes for local uploads. However, there is also an s3-uploads plugin that stores your files in S3 storage, the cost of which is very reasonable. This would probably be the best option for you if you expect a lot of uploads.

And also this github issue:
https://github.com/akhoury/nodebb-plugin-import/issues/93

@DecentM Am I understanding it wrong? 
Anyway, this is not that big of deal. Please focus on the double stylus header in *.user.css at least.

**Comment by DecentM** [comment]
Thanks for the research! I'll look into the links you posted in the next maintenance window.

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#2
