### ISSUE TITLE
Error: No content

### ISSUE THREAD

**Issue by jerone** [OpenUserCSS/openusercss.org#5]
Just tried to create a theme, but i'm getting a red error: No content. From what I can see I've filled in every (required) fields...

![2017-12-28 19_51_43-openusercss](https://user-images.githubusercontent.com/55841/34420228-bc4495b8-ec08-11e7-82d1-aafda4b8c1cc.png)

**Comment by DecentM** [comment]
Thanks for the report! A release with a fix for this in building as we speak (https://github.com/OpenUserCSS/openusercss.org/commit/750dc97d47bf88b66efe2c55b11db6ca3bc05611)

**Comment by DecentM** [comment]
It should be fixed, can you confirm?

**Comment by DecentM** [comment]
I've not seen this pop up anymore, but feel free to comment if you still get this.

**Comment by jerone** [comment]
I had to use DevTools to clear the cache, but after that I didn't get *this* error anymore. I can't upload yet, because of error "You must verify your e-mail address before uploading themes." (issue https://github.com/OpenUserCSS/openusercss.org/issues/2).
