### ISSUE TITLE
Chat - conversation switching 

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#52]
So when you click on another user you are supposed to switch to their conversation with you right? For some reason it doesn't let me to do it.

I should be on your chat. I am not.
![image](https://user-images.githubusercontent.com/19552720/34606529-712d8768-f218-11e7-912e-0e9c2c6dfa6c.png)

**Comment by RaitaroH** [comment]
Also, if I don't have any chat opened the problem is still there. BUT if I click the button to minimize the chat in it's window then it switches to the appropriate chat, for some reason.

**Comment by DecentM** [comment]
Hmm.. if you refresh the page after switching, does the correct one show?

**Comment by RaitaroH** [comment]
Yes.

**Comment by DecentM** [comment]
Okay, I'll put this on the list of tasks for the next maintenance. Thanks!

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#1
