### ISSUE TITLE
Theme validation not reset

### ISSUE THREAD

**Issue by jerone** [OpenUserCSS/openusercss.org#53]
After trying to create a theme with a missing description, it shows an error. Adding the missing description, doesn't enable the "Save theme" button. Same goes for all other required fields.

Edit: 
![2018-01-05 22_22_49-openusercss](https://user-images.githubusercontent.com/55841/34629134-577d74be-f267-11e7-839b-8c225d8fc175.png)

**Comment by DecentM** [comment]
Very nice and straightforward report, thanks!

**Comment by DecentM** [comment]
This also affects the login and register pages.

**Comment by DecentM** [comment]
The release that includes this fix is live. Look out for version a8ddaaf in the footer!
