### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Mottie** [OpenUserCSS/openusercss.org#55]
The theme's screenshot may need a custom position setting; or to always have the top visible.

For example, the [GitHub Fixed Header](https://openusercss.org/theme/5a514de3d4c8c00b00837103/%7B%22viewingSource%22%3Afalse%7D) style's screenshot includes the fixed header but it isn't visible in the screenshot

Original image

![](https://user-images.githubusercontent.com/136959/34721735-8829b6b4-f509-11e7-913c-a5b763df3343.png)

How it looks when the theme page is expanded beyond 1200px

![](https://user-images.githubusercontent.com/136959/34721709-74690de6-f509-11e7-8121-c4d7780d7749.png)

**Comment by DecentM** [comment]
For some reason, this is indended (as in I put `center center` in the flush-img component), but yes, I'll change this.
Thanks!

**Comment by RaitaroH** [comment]
@DecentM  Maybe this issue is relevant for this. The screenshot is not centered.
![image](https://user-images.githubusercontent.com/19552720/34774582-88a7857a-f618-11e7-885f-50c4a09d889c.png)

**Comment by DecentM** [comment]
It's not centered anymore, because the top of the image is now always visible at the top of the image frame. Screenshots of sites usually have important stuff there, like site headers, etc.

**Comment by RaitaroH** [comment]
Ok. It is better for everyone else I guess.

**Comment by DecentM** [comment]
You can just move your text up if you want, but I recommend actually taking a screenshot of the site with the theme applied, so users of your themes know what they're installing.

**Comment by RaitaroH** [comment]
Yeah... that does't work for my themes. 
https://github.com/OpenUserCSS/OpenUserCSS-DeepDark#colors
You know? All of this custom colors just make a screenshot sorta... wrong or incomplete.

**Comment by Mottie** [comment]
I think adding an option to allow the developer to set the image position would solve this issue, e.g. "center top" or "center center".

**Comment by DecentM** [comment]
> All of this custom colors just make a screenshot sorta... wrong or incomplete.  

You can put multiple screenshots, just click "add screenshot" again.  

> I think adding an option to allow the developer to set the image position would solve this issue  

I feel like there has to be a better solution, like adaptive frame size, or maybe a lightbox.
