### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#56]
I was trying to upload my YouTube DeepDark Classic and it is too large. (ALSO damn, do I love that the tile, version and description get filled in thx to the stylus header, nice)
Console output:
```
Error: Network error: Network request failed with status 413 - "Request Entity Too Large"
Stack trace:
ApolloError@https://openusercss.org/browser.js:1:73462
[4]</</</QueryManager</QueryManager.prototype.mutate/</<@https://openusercss.org/browser.js:1:98104
run@https://openusercss.org/browser.js:1:1121074
notify/<@https://openusercss.org/browser.js:1:1121306
flush@https://openusercss.org/browser.js:1:1052927
MutationCallback*[220]</module.exports@https://openusercss.org/browser.js:1:1053333
[360]<@https://openusercss.org/browser.js:1:1119901
s@https://openusercss.org/browser.js:1:9611
s/<@https://openusercss.org/browser.js:1:9670
[478]<@https://openusercss.org/browser.js:1:1186111
s@https://openusercss.org/browser.js:1:9611
s/<@https://openusercss.org/browser.js:1:9670
[11]</<@https://openusercss.org/browser.js:1:161978
[11]<@https://openusercss.org/browser.js:1:161835
s@https://openusercss.org/browser.js:1:9611
s/<@https://openusercss.org/browser.js:1:9670
[708]</<@https://openusercss.org/browser.js:1:2920600
[708]<@https://openusercss.org/browser.js:1:2919880
s@https://openusercss.org/browser.js:1:9611
e@https://openusercss.org/browser.js:1:9785
@https://openusercss.org/browser.js:1:9376
@https://openusercss.org/browser.js:1:9332
@https://openusercss.org/browser.js:1:903
```

**Comment by RaitaroH** [comment]
https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkClassic.user.css
It is 1215 lines, but still.

**Comment by DecentM** [comment]
I'm glad you like it!
That's quite a large theme, I think the default body-parser limit of 100kb is a bit too small, so I raised it to 120kb. Unfortunately I can't raise it more until I'm able to get some ongoing funding to cover server costs. Right now, it's running on a cheap VPS with not a lot of storage.

**Comment by RaitaroH** [comment]
Yeah but  84.9 KB < 100KB so....

**Comment by DecentM** [comment]
I just realised why this is the way it is.
The limit is on the *entire* request size, not the theme size. The reason this happened is because the request you sent included a bunch of metadata alongside the theme.

For now, I'll leave this issue closed though, but I want to implement some sort of minifier into the theme editor eventually.

**Comment by Mottie** [comment]
Hmm, I just tried to create GitHub-Dark on the site...

The style itself is 206KB, while the variables JSON file is 196KB. I guess we'll be hosting it on GitHub for a bit. I wish I could help with funding, but we got a baby on the way.

**Comment by DecentM** [comment]
Don't worry about it Mottie, life comes first for everyone, I think. Once I'm finally able get the GH integration implemented, theme size will no longer be an issue. :1st_place_medal:

**Comment by eight04** [comment]
> Once I'm finally able get the GH integration implemented, theme size will no longer be an issue,

Does it mean that the style won't be hosted on OUCSS and OUCSS points the installation/update URL to Github?
