### ISSUE TITLE
Adding a new theme

### ISSUE THREAD

**Issue by Mottie** [OpenUserCSS/openusercss.org#6]
I attempted to open this page and noticed a bunch of errors in the console. Only *after* installing the Vue DevTools chrome extension was I able to get the page to load properly.

**Comment by DecentM** [comment]
I can't reproduce this. I tried Chrome and Firefox with, or without Vue devtools.
Can you elaborate on your environment? I'm looking for: operating system, your Chrome version, other extensions.
If you have anything else you think could create this bug, let me know.
Please also attach a screenshot of the expanded error message, so I can start tracking it down!

**Comment by Mottie** [comment]
Ahh, you're right... it might have been the lag I was experiencing and a script didn't load. It's working fine now.
