### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#61]
This link (from #60 ) redirects to a page that looks like this:
![image](https://user-images.githubusercontent.com/19552720/34735053-adcad2aa-f576-11e7-9054-62d0f31652d2.png)

Now... would be nice to take from the url and suggest the proper link for the theme itself. 

Also... I have to say that the page is kinda meh. I mean your shrug emoji that you used for not found screenshots would be better. A 404 image page kinda like github is quite nice, in my opinion.

**Comment by RaitaroH** [comment]
Would be kinda awesome to poke fun at userstyles.org somehow. Maybe like:
```Hmmm... if this was userstyles.org you will get more than just a broken link.```

**Comment by DecentM** [comment]
I'm pretty happy with the current 404 page, but I got the idea of having everyone suggest designs for it.  
If anyone has some time, please design a not found page and post it in the forums (preferably in .png or .svg): https://forums.openusercss.org/topic/12/not-found-designs

I'm trying to distance the site from us.o (this is why I keep calling themes themes, for example), so I'd prefer not to have a reference.

**Comment by RaitaroH** [comment]
Very nice. I will see what I can come up with.
The current 404 is... too... ahm... polite I guess. Idk, I have someone in college like that... to japanese people he would seem to nice and polite.

**Comment by DecentM** [comment]
I'll close this issue, since there doesn't seem to be a lot of interest in this, but I always welcome ideas and mockups either on the forums or here!
