### ISSUE TITLE
Theme statistics

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#63]
You know, stuff like how many uploads per month etc. 

I would like to also have some edit button somewhere in the theme box:
![screenshot_20180109_201018](https://user-images.githubusercontent.com/19552720/34735741-258ed244-f579-11e7-8edc-65e5321d3feb.png)
That is for easier edits. (GITHUB LINKING WOULD MAKE THIS OBSOLETE FOR ME BUT.... XD)

**Comment by DecentM** [comment]
Thanks for the reminder!
External importing would probably consist of an import button, so after it's imported, the theme will be available to edit on the site itself, so this is doubly relevant.

**Comment by DecentM** [comment]
Theme statistics are now up! :tada:  
Please follow https://github.com/OpenUserCSS/openusercss.org/issues/7 for the import feature
