### ISSUE TITLE
External theme sourcing

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#7]
Enable sourcing themes from GitHub, gists or any site.
This feature would make theme authors' job way easier.

**Comment by RaitaroH** [comment]
I suppose linking to an external file such as:
```
https://raw.githubusercontent.com/OpenUserCSS/OpenUserCSS-DeepDark/master/OpenUserCSSDeepDark.user.css
```
or
```
https://rawgit.com/OpenUserCSS/OpenUserCSS-DeepDark/master/OpenUserCSSDeepDark.user.css
```
will work really well. 
If you can do that I am sure it could easily work with other websites like Dropbox and such.

**Comment by the-j0k3r** [comment]
Would be good because some themes are just too big for website.

OUCSS would probably also need to do some checking to make sure the external theme is safe.

**Comment by the-j0k3r** [comment]
You can also use Gists as theme sources :) Works pretty well but the update URL isnt obvious.

Take this for instance (collaboration with StylishThemes job) https://gist.github.com/the-j0k3r/e11d791a22b1354106c2fe56222e0927

Thats the home URL for update URL you use https://gist.github.com/the-j0k3r/e11d791a22b1354106c2fe56222e0927/raw

**Comment by RaitaroH** [comment]
Yeah gist do work too. You only need to have the user.css file

**Comment by the-j0k3r** [comment]
Yea, I forgot to mention, but yep :)

**Comment by DecentM** [comment]
Superseded by https://github.com/OpenUserCSS/openusercss.org/issues/115

**Comment by the-j0k3r** [comment]
superseded? funny.
