### ISSUE TITLE
Connection to Openusercss was lost

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#72]
Whenever I log in to the forum, the following message appears:
`Looks like your connection to OpenUserCSS was lost, please wait while we try to reconnect.`
I can't post or send any chat messages.

**Comment by DecentM** [comment]
I'm unable to reproduce this, can you post some details about your environment? (OS version, browser, extensions, etc)

**Comment by DecentM** [comment]
This issue was moved to OpenUserCSS/forums.openusercss.org#8
