### ISSUE TITLE
Sort themes not by date of upload but by name

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#79]
Or you know, have an option or something. I have to many themes and I always spend a bit too many seconds looking for what I need to update.

XD you added guidelines. Nice.

**Comment by DecentM** [comment]
This sounds like a reasonably straightforward feature.  
I'd be glad to accept a PR if you want to have a stab at it!  
([CONTRIBUTORS.md is a good place to start, just in case you haven't read it all](https://github.com/OpenUserCSS/openusercss.org/blob/master/CONTRIBUTING.md))

**Comment by sak6e** [comment]
I want to contribute. I've never contributed before. What do I need to know to fix this issue?

**Comment by sak6e** [comment]
Hey @DecentM,
I'm facing some problems in setting up my environment. PFA a screenshot of
the problem that I'm facing.
Please help me with it. I'm sure I'd be of help to the project once it's
all set up!
Thank You.
-sak6e

**Comment by DecentM** [comment]
I couldn't find the screenshot you're talking about, I don't think GitHub supports e-mail attachments. Can you upload it in the web UI?

**Comment by sak6e** [comment]
@DecentM  Even after running the yarn command, which should have installed all the dependencies in package.json, I'm getting errors for individual dependencies.
![yarn](https://user-images.githubusercontent.com/22349909/40272282-7fa62038-5bc8-11e8-8029-93865d6d8800.png)

**Comment by DecentM** [comment]
Ah I see, apparently I left out generating the licenses.json file from the client chain. I've made a fix for this, but in the meantime, please run `yarn dev:env gulp licenses`. This will generate the missing file for you, and you won't need to run it again for the foreseeable future.

**Comment by DecentM** [comment]
Also, while it should be totally possible to run everything with Yarn, I'd recommend to set up Docker, since that will ensure that your environment is the same one I and the production server runs.  
If you have Docker installed and set up, you should just be able to run `./start.sh`. It will check if everything's good and start the tasks automatically.

**Comment by sak6e** [comment]
When I run the command: yarn env:dev gulp licenses
it says: Command "env:dev" not found.

**Comment by DecentM** [comment]
It looks like it's in the `package.json`, yarn should see it.  
I can think of a couple of reasons it doesn't work:
- Make sure you're on the `v1.0.0` branch, not `master`  
- Make sure you're in the right directory

If you assert those and it still doesn't work, can you post the package.json file here?

**Comment by sak6e** [comment]
[(packagejson).txt](https://github.com/OpenUserCSS/openusercss.org/files/2055096/packagejson.txt)
I checked the two things you mentioned. It still doesn't work. I've posted the package.json file as a txt file.

**Comment by DecentM** [comment]
It looks like you have an older version of the package.json file, which I changed 11 days ago.  
Do `git pull` to get the latest version!

**Comment by sak6e** [comment]
Okay, now I've pulled all the changes and updated my repo
Now when I fire: yarn watch
it says: Cannot find module 'git-revision'

**Comment by DecentM** [comment]
That message typically comes up when dependencies aren't installed. I think you should be able to continue from [step 6](https://github.com/OpenUserCSS/openusercss.org/blob/v1.0.0/CONTRIBUTING.md#setting-up-your-development-environment)

**Comment by sak6e** [comment]
I had already run the command 'yarn' after updating. But I haven't done step 7. Could it be making any difference?

**Comment by DecentM** [comment]
<img src="https://sd.keepcalm-o-matic.co.uk/i-w600/hello-i-m-dumb.jpg" height="200"/>  
This is already fixed, I just forgot the push the update...  
So please do `git pull` and then `yarn` again and it should be working

**Comment by DecentM** [comment]
The app needs to connect to a MongoDB instance (that will store accounts and themes), start one, then you can set the `OUC_DATABASE_MAIN` environment variable in your `.env.local` file. (Copy the .env file to .env.local if you don't have one.) If you're running it on the same machine you're running the app on, it's `mongodb://localhost:27017/openusercss-main`  

This is missing from the documentation, I'll update it in a few. Thanks!

**Comment by DecentM** [comment]
Hey, @sak6e, you still working on this? I have the opportunity to fix this issue now, so if you don't feel like it, I can do ahead with a solution

**Comment by sak6e** [comment]
@DecentM Sorry, I couldn't work on it, my Ubuntu crashed. Please go ahead with the solution.

**Comment by DecentM** [comment]
I'm not too familiar with Ubuntu, but it can be quite fun to take a shot at reviving a borked system :smile:  
Thanks for replying, I'm building a release as we speak! :tada:

**Comment by sak6e** [comment]
@DecentM Thanks for being willing to help! Although I've removed Ubuntu from my system now, I can still show you what was happening if you want. Maybe we can talk about that somewhere else?

**Comment by DecentM** [comment]
I'm on the forums if you wanted to talk, or you can e-mail me on the address on my profile :+1:
