### ISSUE TITLE
Links in theme description are unrecognizable

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#83]
Links added to the description of a theme are unrecognizable as such when viewing the theme's page. Generally they should be styled in a way that makes it obvious that you can interact with them (classically in blue color).

## Environment details
  - Site version: 0.9.7
  - Browser and version: Firefox 59.0.1
  - Installed extensions: Tons, but not presumed relevant unless this proves hard to confirm.

**Comment by DecentM** [comment]
Indeed, it looks like something is overriding the text colour.  
Related to https://github.com/OpenUserCSS/openusercss.org/issues/49
