### ISSUE TITLE
@advanced dropdown stylus options are removed from the code

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#86]
Anything with `@advanced dropdown` is getting removed from my MAL theme. It works fine if you install it from github. [Here](https://github.com/RaitaroH/MyAnimeList-DeepDark/commit/68e939e3e96d1e9df13224079a8024cd1bfacaef) is the commit when I added logo choosing options. This gets removed in the code on openuser.

## Steps to Reproduce the Problem

  1. Install my theme from the site, https://openusercss.org/theme/5a54ffd81bf0fd0b00422ad4
  1. Look at the code, the @advanced is missing

## Environment details

  - Site version: v0.9.7
  - Browser and version: Firefox Nightly 
  - Installed extensions: 59.0.2
  - Operating system: KDE Neon.

----

**Comment by DecentM** [comment]
Thanks for the concise bug report! I think this is related to #84, so I'll track this there :+1:
