### ISSUE TITLE
Large styles fail to submit

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#89]
## Set up
1. Paste a large userstyle (tested with 2443 lines, 65000 bytes) into the input field.
2. Press 'Save theme'
## Expected Behavior
1. The style is uploaded and saved, editing is finished and it becomes available on the site.
## Actual Behavior
1. Editing does not finish, instead only an error message is shown depending on style size.

## Environment details
  - Site version: 0.9.7
  - Browser and version: Firefox 59.0.2
  - Operating system: Linux Fedora

## Related
#84 / #70  ???
----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>
  ```
    Error: GraphQL error: Cannot read property '2' of null
    Stack trace:
    ApolloError@https://openusercss.org/browser.js:1:78919
    [4]QueryManager QueryManager.prototype.mutate @https://openusercss.org/browser.js:1:102387
    run@https://openusercss.org/browser.js:1:1126531notify @https://openusercss.org/browser.js:1:1126763
    flush@https://openusercss.org/browser.js:1:1058384
  ```

<superscript> fucking markdown </superscript>
</details>

PS: I'm also hitting #56 with larger styles but my understanding is that on current hosting there is little we can do to fix this (currently sitting at 85.3kB total).

**Comment by DecentM** [comment]
Thanks for the report!   :+1: 
This is the same error message as #70, so I'm tracking this there as well.

(by the way, the reason your stack trace didn't render right is that there needs to be an empty line between markdown and HTML)
