### ISSUE TITLE
"@homepageURL" causes "i is not a constructor"

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#90]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| no error is displayed | "An error occurred in the editor: i is not a constructor" is displayed |

## Steps to Reproduce the Problem

  1. Start creating a new theme
  1. Enter the following in the edit box:
```
/* ==UserStyle==
@homepageURL
```

## Environment details

  - Site version: 1.0.0
  - Browser and version: Firefox 60.0
  - Installed extensions: Stylus
  - Operating system: Fedora 26

----

**Comment by DecentM** [comment]
Thanks for reporting!
It looks like parsing fails if the usercss metadata is incomplete.

**Comment by hyperfekt** [comment]
Not at all, I just posted the minimum needed to reproduce the bug. In fact
it is completely irrelevant what follows this example or if any other
usercss fields come before this one.

**Comment by DecentM** [comment]
I can't reproduce it, does it happen if you close the comment?

**Comment by hyperfekt** [comment]
Yes, definitely. Case is relevant, are you entering the snippet I posted exactly like that?

**Comment by DecentM** [comment]
Yep, I copy-pasted it. Tried in both Firefox and Chromium, but it went through in all cases (https://openusercss.org/theme/5b0c4931dad9d20b00d6c05f).  
Please try to fiddle with the input to see exactly what causes the error!  

I also can't see any error with "constructor" in the text in Sentry. Can you try disabling extensions/trying in another browser to see if the issue is consistent?

**Comment by hyperfekt** [comment]
It occurs even with a completely fresh profile. The link you gave is not on staging, afaik the error occurs only there (as indicated by the version 1.0.0), not on the live site.

**Comment by DecentM** [comment]
Oh that's now, I should put something in the issue template that asks for the environment.
I'll test it in staging tomorrow.

**Comment by DecentM** [comment]
I found the cause of this and fixed it in 1.0.0 :tada:
