### ISSUE TITLE
Can't delete theme

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#93]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| Clicking `Delete theme` after entering the title to confirm will delete the theme | No reaction beyond CSS focus state applied to button |

## Steps to Reproduce the Problem

  1. Create any theme
  1. Visit that theme's page
  1. Click `Delete theme`
  1. Enter theme's title as confirmation in popup
  1. Observe the button labeled `Delete theme` in the popup become active
  1. Click that button

## Environment details

  - API version: heads/v1.0.0 (unreleased)
  - Client version: 1.0.0
  - Browser and version: Firefox 60.0
  - Installed extensions: None
  - Operating system: Fedora 26

----
(No output appears in the console)

**Comment by DecentM** [comment]
Thanks for the report!

**Comment by DecentM** [comment]
Fixed in https://github.com/OpenUserCSS/openusercss.org/commit/0cc0773bc0fc5405397f053f27a191be7085800c :tada:
