### ISSUE TITLE
Double footer on 404 page

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#96]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| one footer | buy one get one free |

## Steps to Reproduce the Problem

  1. navigate to e.g. https://openusercss.org/assets/images/cover-default.png
  1. observe 2 footers
  1. keep looking at it, its really lovely and memorising :smile: 

![screenshot-2018-6-12 openusercss](https://user-images.githubusercontent.com/31389848/41291364-67edef98-6e47-11e8-85e6-dbcfbdb7828b.png)

## Environment details

  - Site version: 1.1.0
  - Browser and version: FF 66.0.2
  - Installed extensions: NA
  - Operating system: WIndows 10 pro but Linux also :)

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
Oh, nice! I think I'll put a third one in :laughing: 
<sub>Thanks!</sub>

**Comment by the-j0k3r** [comment]
Why settle for 3, go all out to infinity and beyond like Buzz Light year and @RaitaroH (im only teasing you dont be upset) :+1:
